### ISSUE TITLE
Same description for two different parameters

### ISSUE THREAD

**Issue by hotblade** [input-output-hk/cardano-docs.iohk.io#93]
On Cardano SL Updater page, `bvdUpdateProposalThd` and `bvdUpdateImplicit` have same description. I think `bvdUpdateProposalThd` has wrong description.

**Comment by ChShersh** [comment]
Thanks for you to notice that! This error will be fixed after this PR https://github.com/input-output-hk/cardano-docs.iohk.io/pull/96 finished and merged to `master`.
